import type { DiagramComponent } from "./types";

export function componentsSection(
  owner: string,
  repo: string,
  branch: string,
  components: DiagramComponent[]
): string {
  if (components.length === 0) return "";
  const lines = [
    "## Components",
    "",
    ...components.map((c) => {
      const link = `[${c.file_path}](https://github.com/${owner}/${repo}/blob/${branch}/${c.file_path})`;
      return c.summary ? `- **${c.label}** — ${link}. ${c.summary}` : `- **${c.label}** — ${link}`;
    }),
  ];
  return lines.join("\n");
}

export function explanationToMarkdown(
  owner: string,
  repo: string,
  branch: string,
  explanation: string,
  components: DiagramComponent[]
): string {
  const parts = [
    `# How ${repo} works`,
    "",
    `> Generated by GitChart · repository \`${owner}/${repo}\` · branch \`${branch}\``,
    "",
    explanation.trim(),
  ];
  const comp = componentsSection(owner, repo, branch, components);
  if (comp) parts.push("", comp);
  return parts.join("\n") + "\n";
}
